# Generated by Django 3.2.14 on 2022-07-14 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Pokemon",
            fields=[
                (
                    "id",
                    models.IntegerField(
                        primary_key=True, serialize=False, verbose_name="id"
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Name")),
                ("weight", models.FloatField(verbose_name="Weight")),
                ("height", models.FloatField(verbose_name="Height")),
                ("stats", models.JSONField(verbose_name="stats")),
                ("evolutions", models.JSONField(verbose_name="evolutions")),
            ],
        ),
    ]
