# Generated by Django 3.2.14 on 2022-07-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pokeapi_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
